[program:qgi2-w27b-dflash2]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/qgi2-w27b-dflash2.sh
autostart=false
autorestart=unexpected
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
