[program:qgi2-dgemma]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/qgi2-dgemma.sh
autostart=false
autorestart=unexpected
startsecs=120
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
